services:
  - type: redis
    name: enlighten-ed-redis
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
    plan: free 
    maxmemoryPolicy: noeviction 

  - type: web
    name: enlighten-ed-world
    env: python
    workingDirectory: .
    buildCommand: |
      cd server && pip install -r requirements.txt
      # Add any frontend build steps here if needed
    preDeployCommand: |
      cd server && python -m flask db init || true
    startCommand: |
      cd server && python -m flask db upgrade && PYTHONPATH=$PYTHONPATH:. gunicorn "app:create_app('production')" --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app
      - key: SESSION_TYPE
        value: redis
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: enlighten-ed-redis
          property: connectionString
      - key: GOOGLE_CALLBACK_URL
        value: https://enlighten-ed-world-hgv2.onrender.com/auth/google/callback
      - key: GITHUB_CALLBACK_URL
        value: https://enlighten-ed-world-hgv2.onrender.com/auth/github/callback
    routes:
      - type: rewrite
        source: /*
        destination: /
